# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vikram Tiwari - Blog
email: vikramtheone1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I write about random things, mostly concerning technologies revolving around
  web technologies. I focus mostly on performance, scaling and building web a
  better place. You will find my low tolerance for bogus websites on Internet
  mentioned a lot here.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://vikramtiwari.com" # the base hostname & protocol for your site
twitter_username: vikram_tiwari
github_username:  vikramtiwari

# Build settings
markdown: kramdown
