# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vikram Tiwari - Blog
mailText: Get in Touch
email: vikramtheone1@gmail.com
websiteName: Personal Website
website: http://vikramtiwari.com
description: > # this means to ignore newlines until "baseurl:"
  This is where I write mostly about random things concerning technologies around
  web while generally focusing on performance, scaling and usability.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.vikramtiwari.com" # the base hostname & protocol for your site
twitter_username: vikram_tiwari
github_username:  vikramtiwari

# Build settings
markdown: kramdown
